app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('catalog/', include('goods.urls', namespace='catalog')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/goods/urls.py
from django.urls import path, include

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('product/', views.product, name='product')
]

app/main/urls.py
from django.urls import path, include

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

app/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

app/goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_image', blank=True, null=True, verbose_name='Изоображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def display_id(self):
        return f'{self.id:05}'

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    about = models.TextField(blank=True, null=True, verbose_name="Описание")

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

app/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

app/goods/views.py
from django.shortcuts import render

from goods.models import Categories, Products


def catalog(request):
    goods = Products.objects.all()
    categories = Categories.objects.all()

    context = {
        'goods': goods,
        'categories': categories
    }
    return render(request, 'goods/catalog.html', context)


def product(request):
    return render(request, 'goods/product.html')

app/main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

app/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


@csrf_exempt
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            user = form.instance
            auth.login(request, user)

            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)


def users_cart(request):
    return render(request, 'users/users_cart.html')


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:index' %}">Mind Games Project</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Информация
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item  text-white" href="#">Как начать играть</a></li>
                            <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                            <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="{% url 'catalog:index' %}">Магазин</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="#">Корзина</a>
                    </li>
                    <li>
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Мой профиль
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item  text-white" href="{% url 'user:profile' %}">Личный кабинет</a>
                            </li>
                            <li><a class="dropdown-item  text-white" href="/admin">Админ панель</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item  text-white" href="{% url 'user:login' %}">Войти</a>
                            <li><a class="dropdown-item  text-white" href="{% url 'user:logout' %}">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>
</header>

{% block content %}
{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/goods/product.html
{% extends "base.html" %}
{% load static %}
{% block title %}Товар{% endblock %}
{% block content %}
<div class="row m-5" style="marging: 50px">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                     class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: 002654</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                 aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                                 class="img-fluid" alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>150.00 $</strong></p>
            <h5 class="card-title">Чайный столик и три стула</h5>
            <p class="card-text">Комплект из трёх стульев и дизайнерский столик для гостинной
                комнаты.</p>
            <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<div class="banner-container">
    <img src="https://i.postimg.cc/63yvfmYN/Banner.png" alt="Banner Image" class="banner-img">
    <div class="banner-text">
      <h2>Welcome to Our Website</h2>
      <p>Discover our amazing products and enjoy special offers! Check out our new collection now.</p>
    </div>
  </div>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Авторизация{% endblock %}
{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form  action="" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" id="id_username"
                        placeholder="Введите ваше имя пользователя"
                        required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" name="password" id="id_password"
                        placeholder="Введите ваш пароль" required>
                    </div>


                    {% comment %} {% for item in form %}
                    <div class="mb-3">
                        <label for="{{ item.id_for_label }}" class="form-label">{{ item.label }}</label>
                        {{item}}
                    </div>
                    {% endfor %} {% endcomment %}


                    {% comment %} <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        {{ form.password }}
                    </div> {% endcomment %}


                    {% comment %} <div class="mb-3">
                        <label for="username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                    </div> {%endcomment%}


                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url 'user:registration' %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="#" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="#" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="#" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Личный кабинет{% endblock %}
{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="#"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->


            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                    </div>
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Введите вашу фамилию" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введите пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}